//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DG.UIGHFSample.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class commentsuseful
    {
        public int commentsuseful_id { get; set; }
        public int comments_id { get; set; }
        public byte commentsuseful_points { get; set; }
    
        public virtual comments comments { get; set; }
    }
}
