//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DG.UIGHFSample.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class posts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public posts()
        {
            this.comments = new HashSet<comments>();
            this.poststotags = new HashSet<poststotags>();
        }
    
        public int posts_id { get; set; }
        public int blogs_id { get; set; }
        public string posts_title { get; set; }
        public string posts_text { get; set; }
        public string posts_username { get; set; }
        public string posts_email { get; set; }
    
        public virtual blogs blogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comments> comments { get; set; }
        public virtual postsadditionals postsadditionals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<poststotags> poststotags { get; set; }
    }
}
