//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DG.UIGHFSample.Model.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dguighfsamplemodelContext : DbContext
    {
        public dguighfsamplemodelContext()
            : base("name=dguighfsamplemodelContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<blogs> blogs { get; set; }
        public virtual DbSet<comments> comments { get; set; }
        public virtual DbSet<commentsuseful> commentsuseful { get; set; }
        public virtual DbSet<posts> posts { get; set; }
        public virtual DbSet<postsadditionals> postsadditionals { get; set; }
        public virtual DbSet<poststotags> poststotags { get; set; }
        public virtual DbSet<tags> tags { get; set; }
    }
}
