//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DG.UIGHFSample.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class poststotags
    {
        public int posts_id { get; set; }
        public int tags_id { get; set; }
        public string poststotags_comments { get; set; }
    
        public virtual posts posts { get; set; }
        public virtual tags tags { get; set; }
    }
}
